module.exports = [
  { name: "- select an example -" },
  { name: "Example 1a: Block Scope: ES5 var",
      base: "02/ex1-block-scope/a", layout: "es5", js: true },
  { name: "Example 1b: Block Scope: ES2015 let",
      base: "02/ex1-block-scope/b", layout: "es6,es5", js: true },
  { name: "Example 2a: Fat Arrow Functions: ES5 Function Repetition",
      base: "02/ex2-fat-arrow-functions/a", layout: "es5", js: true },
  { name: "Example 2b: Fat Arrow Functions: ES2015 version",
      base: "02/ex2-fat-arrow-functions/b", layout: "es6,es5", js: true },
  { name: "Example 2c: Fat Arrow Functions: Incorrect this",
      base: "02/ex2-fat-arrow-functions/c", layout: "es5", js: true },
  { name: "Example 2d: Fat Arrow Functions: Corrected this",
      base: "02/ex2-fat-arrow-functions/d", layout: "es5", js: true },
  { name: "Example 2e: Fat Arrow Functions: ES2015 method",
      base: "02/ex2-fat-arrow-functions/e", layout: "es6,es5", js: true },
  { name: "Example 3a: Object Definitions: ES5",
      base: "02/ex3-object-definitions/a", layout: "es5", js: true },
  { name: "Example 3b: Object Definitions: ES2015",
      base: "02/ex3-object-definitions/b", layout: "es6,es5", js: true },
  { name: "Example 4a: Default Arguments: ES5",
      base: "02/ex4-default-arguments/a", layout: "es5", js: true },
  { name: "Example 4b: Default Arguments: ES2015",
      base: "02/ex4-default-arguments/b", layout: "es6,es5", js: true },
  { name: "Example 5a: Variable Arguments: ES5 Sum",
      base: "02/ex5-variable-arguments/a", layout: "es5", js: true },
  { name: "Example 5b: Variable Arguments: ES2015 Sum",
      base: "02/ex5-variable-arguments/b", layout: "es6,es5", js: true },
  { name: "Example 5c: Variable Arguments: ES5 Interpolate",
      base: "02/ex5-variable-arguments/c", layout: "es5", js: true },
  { name: "Example 5d: Variable Arguments: ES2015 Interpolate",
      base: "02/ex5-variable-arguments/d", layout: "es6,es5", js: true },
  { name: "Example 6a: Destructuring: ES2015 examples",
      base: "02/ex6-destructuring/a", layout: "es6,es5", js: true },
  { name: "Example 6b: Named Parameters: ES5",
      base: "02/ex6-destructuring/b", layout: "es5,html", js: true, html: true },
  { name: "Example 6c: Named Parameters: ES2015",
      base: "02/ex6-destructuring/c", layout: "es6,es5,html", js: true, html: true },
  { name: "Example 6d: Multiple Return Values: ES2015",
      base: "02/ex6-destructuring/d", layout: "es6,es5", js: true },
  { name: "Example 7: String Interpolation",
      base: "02/ex7-string-interpolation/a", layout: "es5,es6", js: true },
  { name: "Example 8a: Promises: ES5 Callback v1",
      base: "02/ex8-promises/a", layout: "es5", js: true },
  { name: "Example 8b: Promises: ES5 Callback v2",
      base: "02/ex8-promises/b", layout: "es5", js: true },
  { name: "Example 8c: Promises: ES2015 Promises",
      base: "02/ex8-promises/c", layout: "es5,es6", js: true },
  { name: "Example 8d: Promises: ES2016 Async/Await",
      base: "02/ex8-promises/d", layout: "es5,es6,html", js: true, html:true },
  { name: "Example 9: Classes",
      base: "02/ex9-classes/a", layout: "es5,es6", js: true }
];
